// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users" | "/users/:userId" | "/*";
  };
  "layouts/layout.tsx": {
    id: "layouts/layout";
    page: "/" | "/users" | "/users/:userId";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "pages/users.tsx": {
    id: "pages/users";
    page: "/users" | "/users/:userId";
  };
  "pages/user.tsx": {
    id: "pages/user";
    page: "/users/:userId";
  };
  "pages/no-match.tsx": {
    id: "pages/no-match";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/layout": typeof import("./src/layouts/layout.tsx");
  "pages/home": typeof import("./src/pages/home.tsx");
  "pages/users": typeof import("./src/pages/users.tsx");
  "pages/user": typeof import("./src/pages/user.tsx");
  "pages/no-match": typeof import("./src/pages/no-match.tsx");
};